### PR TITLE
Add support for reading media.yaml

### PR DESCRIPTION
**Pull request by jsarabia**
[Reviewable link](https://reviewable.io/reviews/WycliffeAssociates/kotlin-resource-container/16)

---
This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16)

### CODE REVIEW

**Review by aunger — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16)* status: all files reviewed, 6 unresolved discussions (waiting on @jsarabia)

___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/ResourceContainer.kt, line 50 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-Lzwf6KH21_hdi7h_FP7:-Lzwf6KICjWp4WdpKOpq:beds9ag) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/ResourceContainer.kt#L50)):*
> ```Kotlin
>             }
>             if (accessor.fileExists(MEDIA_FILENAME)) {
>                 this.media = accessor.getReader(MEDIA_FILENAME).use {
> ```

If `media.yaml` doesn't exist then `this.media` should be set to null, not left as an uninitialized lateinit. (I'd prefer never to use lateinit, but that's just me.)
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 6 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-LzwcFB03S0vIMgGeqYe:-LzwcFB03S0vIMgGeqYf:bjs22eo) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L6)):*
> ```Kotlin
> 
> @JsonIgnoreProperties(ignoreUnknown = true)
> data class MediaManifest(
> ```

Since MediaManifest is the top-level object in this file, maybe the filename should be MediaManifest.kt?
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 7 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-Lzwd5_qAu5xtr1AXIzD:-Lzwd5_qAu5xtr1AXIzE:b-k91ax7) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L7)):*
> ```Kotlin
> @JsonIgnoreProperties(ignoreUnknown = true)
> data class MediaManifest(
>     var resource: Resource? = null,
> ```

You're defaulting Strings to empty, but this to null.  Should they be consistent?  (I don't remember Jackson well enough to know.)
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 28 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-Lzwd2USC0m8jgNVbINH:-Lzwd2USC0m8jgNVbINI:b-9i3xqa) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L28)):*
> ```Kotlin
>     var identifier: String = "",
>     var version: String = "",
>     //var contributor: Array<String> = arrayOf(),
> ```

Why commented?
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 31 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-LzwdSvY3c84ha7gSAYC:-LzwdSvZ27ByYuT3avoQ:b-fncjmh) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L31)):*
> ```Kotlin
>     var url: String = "",
>     var quality: List<String> = listOf(),
>     var chapter_url: String= ""
> ```

In other places ([Example](https://github.com/WycliffeAssociates/kotlin-resource-container/blob/master/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Manifest.kt#L8-L9)), we use Kotlin style for element names and map them with `@JsonProperty`.
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 31 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-LzwdppPEennljc1c-0b:-LzwdppPEennljc1c-0c:bir6epe) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L31)):*
> ```Kotlin
>     var url: String = "",
>     var quality: List<String> = listOf(),
>     var chapter_url: String= ""
> ```

Nit: Missing space

**Review by aunger — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/ResourceContainer.kt, line 50 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-Lzwf6KH21_hdi7h_FP7:-M0119tJ4a_4Q8DTmIdT:b-vahosc) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/ResourceContainer.kt#L50)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

If `media.yaml` doesn't exist then `this.media` should be set to null, not left as an uninitialized lateinit. (I'd prefer never to use lateinit, but that's just me.)
</blockquote></details>

Looks good now
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 6 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-LzwcFB03S0vIMgGeqYe:-M011KO76VMVaI4gRx9V:bb6ywmx) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L6)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Since MediaManifest is the top-level object in this file, maybe the filename should be MediaManifest.kt?
</blockquote></details>

LGTM
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 28 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-Lzwd2USC0m8jgNVbINH:-M011rtZ7j6rnM24i3HE:bb6ywmx) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L28)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Why commented?
</blockquote></details>

LGTM
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 31 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-LzwdSvY3c84ha7gSAYC:-M011uqq1j68HPtx2mTj:bb6ywmx) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L31)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

In other places ([Example](https://github.com/WycliffeAssociates/kotlin-resource-container/blob/master/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Manifest.kt#L8-L9)), we use Kotlin style for element names and map them with `@JsonProperty`.
</blockquote></details>

LGTM
___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 31 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-LzwdppPEennljc1c-0b:-M01254j0iweyTr7HOUK:bb6ywmx) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L31)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Nit: Missing space
</blockquote></details>

LGTM

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16)* status: all files reviewed, 1 unresolved discussion (waiting on @aunger)

___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 7 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-Lzwd5_qAu5xtr1AXIzD:-M0IxDX9AJmgN-jurdH4:bsaoor2) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L7)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

You're defaulting Strings to empty, but this to null.  Should they be consistent?  (I don't remember Jackson well enough to know.)
</blockquote></details>

Not everything has a top level resource, so I feel like defaulting things to empty string here would make it more difficult to find if there actually is a resource.

Things like MediaProjects have an entry actually present in the manifest, so I would consider that "part of the form" to be "filled out" in which some optional fields were left blank; but there's still actually an item there.

Really, it's how should an API wrapper around the series of YAML files work. I don't exactly know, to be honest.

**Review by aunger — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt, line 7 at r1](https://reviewable.io/reviews/wycliffeassociates/kotlin-resource-container/16#-Lzwd5_qAu5xtr1AXIzD:-M0Jji4j1qzAdc10A976:b32wtd) ([raw file](https://github.com/wycliffeassociates/kotlin-resource-container/blob/263ec76c378f148dd452f6934d2f68cab5b76677/src/main/kotlin/org/wycliffeassociates/resourcecontainer/entity/Media.kt#L7)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Not everything has a top level resource, so I feel like defaulting things to empty string here would make it more difficult to find if there actually is a resource.

Things like MediaProjects have an entry actually present in the manifest, so I would consider that "part of the form" to be "filled out" in which some optional fields were left blank; but there's still actually an item there.

Really, it's how should an API wrapper around the series of YAML files work. I don't exactly know, to be honest.
</blockquote></details>

ok

**Pull request merged**
